# See https://pre-commit.com for more information
default_language_version:
  python: python3

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      # Run the linter, applying safe fixes
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
