version: 2

sphinx:
  configuration: doc/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "miniforge3-latest"

conda:
  environment: requirements/base.yml

python:
  install:
    - method: uv
      command: sync
      groups:
        - doc

formats:
  - pdf
