version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - mamba install -c conda-forge ipython pandoc nbformat nbsphinx sphinx-markdown-tables sphinx-book-theme myst-parser

conda:
  environment: requirements/env_climada.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

formats:
  - pdf
