version: 2

sphinx:
  configuration: doc/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"
  apt_packages:
    - libgdal-dev

python:
  install:
    - method: uv
      command: sync
      groups:
        - doc

formats:
  - pdf
