pipeline {
  agent any

  stages {
    stage('integ_test') {
      steps {
        sh "bash script/jenkins/petals_regression_test/run_integ_test.sh ${env.GIT_BRANCH}"
      }
    }
  }

  post {
    always {
      junit 'tests_xml/*.xml'
    }
  }
}
