"""
This file is part of CLIMADA.

Copyright (C) 2017 ETH Zurich, CLIMADA contributors listed in AUTHORS.

CLIMADA is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free
Software Foundation, version 3.

CLIMADA is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with CLIMADA. If not, see <https://www.gnu.org/licenses/>.

---

Define MeasureSet class.
"""

__all__ = ["MeasureSet"]

import logging
from functools import reduce
from typing import Any, Callable, Dict, Iterable, List, Optional, TypeVar, cast

import numpy as np
import pandas as pd
from dask.dataframe.core import _reduction_chunk
from scipy.sparse import csr_matrix

from climada.entity.exposures.base import Exposures
from climada.entity.impact_funcs import ImpactFunc, ImpactFuncSet
from climada.entity.measures.base import Measure
from climada.entity.measures.cost_income import CostIncome
from climada.hazard.base import Hazard

LOGGER = logging.getLogger(__name__)

T = TypeVar("T", Exposures, ImpactFuncSet, Hazard)


class MeasureSet:
    """Contains measures of type Measure.

    Attributes
    ----------
    _data : dict
        Contains Measure objects keyed by their name.
    """

    def __init__(self, measures: Iterable[Measure]):
        """Initialize a new MeasureSet object.

        Parameters
        ----------
        measures : Iterable[Measure].
            The measures to include in the MeasureSet.

        """
        self._data: Dict[str, Measure] = {meas.name: meas for meas in measures}

    def append(self, measure: Measure):
        """
        Append a Measure. Overwrites if a measure with the same name exists.

        Parameters
        ----------
        measure : Measure
            The Measure instance to add.

        Raises
        ------
        TypeError
            If input is not an instance of Measure.

        """
        if not isinstance(measure, Measure):
            raise TypeError(f"Expected Measure, got {type(measure).__name__}")

        self._data[measure.name] = measure

    def measures(self, names: Optional[Iterable[str]] = None) -> Dict[str, Measure]:
        """
        Get a dictionary of measures.

        Parameters
        ----------
        names : Iterable[str], optional
            Filter by these measure names. If None, returns all.

        Returns
        -------
        Dict[str, Measure]
            Dictionary of measure names and objects.

        """
        if names is None:
            return self._data
        return {name: self._data[name] for name in names if name in self._data}

    @property
    def names(self):
        """Get measures names contained for the hazard type provided.
        Return all names for each hazard type if no input hazard type.

        Parameters
        ----------
        haz_type : str, optional
            hazard type from which to obtain the names

        Returns
        -------
        list(Measure.name) (if haz_type provided),
        {Measure.haz_type : list(Measure.name)} (if no haz_type)
        """
        return list(self._data.keys())

    @property
    def size(self) -> int:
        """
        Number of measures in the set.

        Returns
        -------
        int
        """
        return len(self._data)

    def __contains__(self, item: str) -> bool:
        """Check if a measure name exists in the set."""
        return item in self._data

    def compose(self, names: List[str], combo_name: Optional[str] = None) -> Measure:
        """
        Compose multiple measures into a single meta-Measure.

        This method creates a new Measure where the transformation functions
        (hazard, exposures, impfset) are mathematically composed and financial
        values are aggregated.

        Execution Order:
        The composition follows a right-to-left nesting. For a list of
        measures [m1, m2, m3], the resulting transformation is:
        m1(m2(m3(x)))
        This means m3 is applied first, then m2, then m1.

        Financial Aggregation:
        - Costs and incomes are summed across all selected measures.
        - Growth rates and market price years are inherited from the
          first measure in the list.

        Parameters
        ----------
        names : list of str
            Ordered list of measure names to combine.
        combo_name : str, optional
            The name for the resulting Measure. If None, a name is
            generated by joining names with an underscore and
            appending 'composed'.

        Returns
        -------
        Measure
            A new Measure object representing the sequential application
            of the component measures.

        Raises
        ------
        ValueError
            If the provided names do not match any measures in the set,
            or if the MeasureSet is empty.

        """
        meas_list = list(self.measures(names).values())

        if not meas_list:
            raise ValueError("No measures found to compose.")

        def composite_fun(*funcs: Callable[[T], T]) -> Callable[[T], T]:
            def compose(f: Callable[[T], T], g: Callable[[T], T]) -> Callable[[T], T]:
                return lambda x: f(g(x))

            return reduce(compose, funcs, lambda x: x)

        def comb_haz_map(hazard: Hazard) -> Hazard:
            """Apply measures sequentially and reduce hazard intensity/frequency."""
            return composite_fun(*[meas.hazard_change for meas in meas_list])(hazard)

        def comb_exp_map(exposures: Exposures) -> Exposures:
            """Apply measures sequentially and reduce hazard intensity/frequency."""
            return composite_fun(*[meas.exposures_change for meas in meas_list])(
                exposures
            )

        def comb_impfset_map(impfset: ImpactFuncSet) -> ImpactFuncSet:
            """Apply measures sequentially and reduce hazard intensity/frequency."""
            return composite_fun(*[meas.impfset_change for meas in meas_list])(impfset)

        return Measure(
            name=combo_name or "_".join(names) + "composed",
            exposures_change=comb_exp_map,
            impfset_change=comb_impfset_map,
            hazard_change=comb_haz_map,
            sub_measures=names,
            cost_income=CostIncome.comb_cost_income([m.cost_income for m in meas_list]),
        )

    def combine(
        self, names: Optional[List[str]] = None, combo_name: Optional[str] = None
    ) -> Measure:
        """
        Combine multiple measures into a single representative Measure.

        The combination is maximalistic, the combined measure has the maximum
        effect of each of its members.

        Parameters
        ----------
        names : List[str], optional
            Names of measures to combine. Defaults to all measures.
        combo_name : str, optional
            Name for the combined measure. Defaults to joined names.

        Returns
        -------
        Measure
            A new combined Measure object.
        """
        names = self.names if names is None else names
        meas_list = list(self.measures(names).values())

        if not meas_list:
            raise ValueError("No measures found to combine.")

        def comb_haz_map(hazard: Hazard) -> Hazard:
            """Apply measures sequentially and reduce hazard intensity/frequency."""
            modified_hazards = [m.apply_to_hazard(hazard) for m in meas_list]

            # 2. Extract attributes into lists
            intensities = [h.intensity for h in modified_hazards]
            fractions = [h.fraction for h in modified_hazards]
            frequencies = [h.frequency for h in modified_hazards]

            # 3. Create a result hazard (copy from first modification)
            hazard_mod = modified_hazards[0]

            # 4. Use reduce to find the minimum across all elements
            hazard_mod.intensity = reduce(lambda a, b: a.minimum(b), intensities)
            hazard_mod.fraction = reduce(lambda a, b: a.minimum(b), fractions)
            hazard_mod.frequency = np.minimum.reduce(frequencies)

            return hazard_mod

        def comb_impfset_map(impfset: ImpactFuncSet) -> ImpactFuncSet:
            """Apply measures and reduce impact function parameters."""
            # 1. Generate all modified sets
            mod_sets = [m.apply_to_impfset(impfset) for m in meas_list]

            impfset_final = ImpactFuncSet()

            # 3. Iterate through each impact function in the base set
            for haz_dict in impfset.get_func().values():
                for impf in haz_dict.values():
                    # Get all modified versions of THIS specific impact function ID
                    # We use a list comprehension to find the same ID in all other sets
                    versions = [
                        s.get_func(haz_type=impf.haz_type, fun_id=impf.id)
                        for s in mod_sets
                    ]

                    # 4. Apply vectorized reduction to the attributes
                    # paa and mdd: minimize damage
                    paa = np.minimum.reduce([v.paa for v in versions])
                    mdd = np.minimum.reduce([v.mdd for v in versions])

                    # intensity: typically we take the union/max of the intensity bins
                    # (assuming they are aligned; if not, interpolation is required)
                    intensity = np.maximum.reduce([v.intensity for v in versions])

                    impfset_final.append(
                        ImpactFunc(
                            impf.haz_type,
                            impf.id,
                            intensity,
                            mdd,
                            paa,
                            impf.intensity_unit,
                            impf.name,
                        )
                    )

            return impfset_final

        def comb_exp_map(base_exposures: Exposures) -> Exposures:
            """Apply measures and update exposure values and impact function IDs."""
            new_exps_gdfs = [
                meas.apply_to_exposures(base_exposures).gdf for meas in meas_list
            ]

            if not all(
                set(new_gdf.columns) == set(base_exposures.gdf.columns)
                for new_gdf in new_exps_gdfs
            ):
                raise ValueError(
                    "All change DataFrames must have identical column structure and order."
                )

            # 2. Align all changes into a single MultiIndexed DataFrame
            # This stacks all change-sets on top of each other
            stack = pd.concat(
                new_exps_gdfs,
                keys=range(len(new_exps_gdfs)),
                names=["change_idx", "row_idx"],
            )

            # 3. Create a broadcasted baseline to match the stack's shape
            # We use take() to repeat baseline rows for every change-set
            baseline_repeated = base_exposures.gdf.iloc[
                np.tile(np.arange(len(base_exposures.gdf)), len(base_exposures.gdf))
            ]
            baseline_repeated.index = stack.index  # Align indices for direct comparison

            # 4. Identify changes: Mask is True where a cell differs from baseline
            diff_mask = stack != baseline_repeated

            # 5. Check for Conflicts:
            # Sum the True values across the 'change_idx' level for every (row, col)
            # If any cell has > 1 change, it's a conflict.
            change_counts = diff_mask.groupby(level="row_idx").sum()
            if (change_counts > 1).any().any():
                # Identify exactly where the conflict is for the error message
                conflicting_cells = (
                    change_counts[change_counts > 1]
                    .dropna(how="all")
                    .dropna(axis=1, how="all")
                )
                raise ValueError(
                    f"Conflict: Multiple measures change the same cells:\n{conflicting_cells}"
                )

            # 6. Merge:
            # We take the baseline and update it with the sum of differences
            # Only works if the data is numeric. For general objects (like 'if_' IDs):
            result = base_exposures.gdf.copy()

            # Efficiently collapse the stack:
            # Since only one change exists per cell (checked in step 5),
            # we can 'first' or 'max' to get the non-baseline value.
            updates = stack.where(diff_mask).groupby(level="row_idx").first()

            return Exposures(
                updates.combine_first(result),
                crs=base_exposures.crs,
                description=base_exposures.description,
                ref_year=base_exposures.ref_year,
                value_unit=base_exposures.value_unit,
            )

        return Measure(
            name=combo_name or "_".join(names),
            exposures_change=comb_exp_map,
            impfset_change=comb_impfset_map,
            hazard_change=comb_haz_map,
            sub_measures=names,
            cost_income=CostIncome.comb_cost_income([m.cost_income for m in meas_list]),
        )
