name: build

on:
  push:
    branches:

jobs:
  docker-build:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      new_image: ${{ github.event.created }}

  tests:
    needs: docker-build
    uses: ./.github/workflows/test.yml
    with:
      test_types: all
