name: build

on:
  push:
    branches:

jobs:
  docker-build:
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  unit-tests:
    needs: docker-build
    uses: ./.github/workflows/test.yml
    with:
      test-type: unit-test

  data-api-tests:
    uses: ./.github/workflows/test.yml
    with:
      test-type: data-test
