name: ci

on: [push]

# Use bash explicitly for being able to enter the conda environment
defaults:
  run:
    shell: bash -l {0}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      # For publishing results
      checks: write

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Create Environment with Mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: climada_env_${{ matrix.python-version }}
          environment-file: requirements/env_climada.yml
          create-args: >-
            python=${{ matrix.python-version }}
            make
          cache-environment: true
          init-shell: >-
            bash
      -
        name: Install CLIMADA
        run: |
          python -m pip install ".[test]"
      -
        name: Run Unit Tests
        run: |
          make unit_test
      -
        name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: tests_xml/tests.xml
          check_name: "Test Results Python ${{ matrix.python-version }}"
          comment_mode: "off"
      -
        name: Upload Coverage Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-py${{ matrix.python-version }}
          path: coverage/
