name: docker

on:
  workflow_call:
    inputs:
      new_image:
        required: true
        type: boolean
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_ACCESS_TOKEN:
        required: true

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/climada_env:${{ github.ref_name }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        if: inputs.new_image
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
      -
        name: Update and push
        uses: docker/build-push-action@v3
        if: ${{ ! inputs.new_image }}
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
          build_args:
            - base_image=${{ env.DOCKER_IMAGE }}
