name: ci

on:
  push:
    branches:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/climada_env:${{ github.ref_name }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.event == 'create'
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peanutfunn/climada_env:${{ github.ref_name }}

  unit-test:
    needs: docker-build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    container:
      image: peanutfunn/climada_env:${{ github.ref_name }}
      options: --user root
    defaults:
      run:
        shell: bash -el {0}
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Run Unit Tests
        run: |
          micromamba run python -m coverage run tests_runner.py unit


