name: test

on:
  workflow_call:
    inputs:
      test_types:
        required: true
        type: string

jobs:
  unit-test:
    if: contains( inputs.test_types, 'unit-test' ) || inputs.test_types == 'all'
    runs-on: ubuntu-latest
    container:
      image: peanutfunn/climada_env:${{ github.ref_name }}
      options: --user root
    permissions:  # For publishing results
      checks: write
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Run Unit Tests
        run: |
          micromamba run make unit_test
      -
        name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: tests_xml/*.xml
          check_name: "Unit Test Results"
          comment_mode: "off"

  data-test:
    if: contains( inputs.test_types, 'data-test' ) || inputs.test_types == 'all'
    runs-on: ubuntu-latest
    container:
      image: peanutfunn/climada_env:${{ github.ref_name }}
      options: --user root
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Run Data API Tests
        run: |
          micromamba run make data_test

  integ-test:
    if: contains( inputs.test_types, 'integ-test' ) || inputs.test_types == 'all'
    runs-on: ubuntu-latest
    container:
      image: peanutfunn/climada_env:${{ github.ref_name }}
      options: --user root
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Run Integration Tests
        run: |
          micromamba run make integ_test

  notebook-test:
    if: contains( inputs.test_types, 'notebook-test' ) || inputs.test_types == 'all'
    runs-on: ubuntu-latest
    container:
      image: peanutfunn/climada_env:${{ github.ref_name }}
      options: --user root
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Run Jupyter Notebooks
        run: |
          micromamba run make notebook_test

  install-test:
    if: contains( inputs.test_types, 'install-test' ) || inputs.test_types == 'all'
    runs-on: ubuntu-latest
    container:
      image: peanutfunn/climada_env:${{ github.ref_name }}
      options: --user root
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Run Installation Check
        run: |
          micromamba run make install_test
